# Generated by Django 6.0.4 on 2026-05-05 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10, verbose_name='Язык')),
                ('phrase', models.TextField(verbose_name='Текст фразы')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Имя пользователя')),
                ('face_path', models.CharField(blank=True, max_length=500, null=True)),
                ('voice_path', models.CharField(blank=True, max_length=500, null=True)),
                ('face_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('voice_print', models.TextField(blank=True, null=True)),
                ('face_encoding', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
