# Generated by Django 6.0.4 on 2026-05-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_photo', models.ImageField(upload_to='recovery/')),
                ('reason', models.CharField(choices=[('forgot_name', 'Забыл уникальный никнейм'), ('face_changed', 'Изменилась внешность/голос'), ('other', 'Другая причина')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Доп. информация от пользователя', null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('approved', 'Одобрено (Разрешена перерегистрация)'), ('rejected', 'Отклонено')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_response_username', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
