# Generated by Django 6.0.4 on 2026-05-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recoveryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryrequest',
            name='suggested_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Предполагаемый никнейм (Авто-поиск)'),
        ),
        migrations.AlterField(
            model_name='recoveryrequest',
            name='admin_response_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ответ админа'),
        ),
        migrations.AlterField(
            model_name='recoveryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Жауап күтілуде (Ожидает)'), ('approved_name', '✅ Никнейм еске салу (Напомнить)'), ('approved_reset', '🔄 Қайта тіркеуге рұқсат (Сброс)'), ('rejected', '❌ Отклонено (Қабылданбады)')], default='pending', max_length=15),
        ),
    ]
